kind: Service
apiVersion: v1
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
        version: v1
    spec:
      containers:
      - name: todoapp
        image: todoapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
