server:
  port: 8080
  host: 0.0.0.0

javax.sql.DataSource:
  todo-db:
    dataSourceClassName: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    dataSource:
      serverName: localhost
      portNumber: 3306
      databaseName: todo-db
      user: user
      password: pass